### ISSUE TITLE
Updates for PU Section

### ISSUE THREAD

**Issue by WiggL** [starcitizendotguide/StarCitizen-Schedule#2]
The Persistent Universe, commonly known as the PU, is a mode of gameplay that allows players to explore the many solar systems (and everything between) that make up the ‘Verse.  Here you and your friends can do missions, engage in ship or FPS combat, and explore asteroid fields for long-forgotten wrecks.  This has all been built on CIG's 64-bit game engine that provides seamless travel from inside a space station, to a spaceship so large that you and your friends can walk around inside while flying thousands of kilometers through space, all in real time and all without load screens.

Moons, much like their larger planetary bodies, are areas in the game that players can fly to and land on.  Although a many number of moons are barren or desolate, some moons can be larger than your typical habitable planet as well as have their own thriving ecosystem.

Surface Outposts are procedurally generated, modular buildings that will be found dotted across the many moons and planets players will be allowed to land and/or dock on.  These outposts will vary in appearance.  What they offer to pilots or merchants will also depend on a variety of variables, such as location and current economic state.

Mission Givers are the plethora of human, alien, kiosk, or any number of avenues where one might obtain details to begin a mission.  Although some Mission Givers may be static in their location and/or prerequisites for being obtained, some Mission Givers may seem someone mundane or obscure, like that discarded piece of trash you absentmindedly kicked as you were heading to a rendezvous point.  A message in a bottle just might net your crew their next month’s salary.

Derelict Ships, and space stations alike, are entities throughout the ‘Verse that may contain a wealth of supplies and information, or be ground zero for a ravaging epidemic.  Regardless of the contents, a series of scans would go a long way to help decide whether to make the detour to check its content or radio back to a scavenging team.

Debris Fields are large masses of flotsam with the potential for lucrative rewards.  Was it the site of an ancient battle containing unheard of technology or materials?  Maybe it was a hauler of precious minerals that taxed its engines a little too hard before they blew.  Regardless of the origin, staying around too long might draw unwanted attention.

Levski is a landing zone on the planet of Delamar located in the Nyx system.

**Comment by sweetcode** [comment]
Thank you very much they are great (commit: 2cbbf79).

**Comment by WiggL** [comment]
I found one minor error after re-editing my work this morning:
"Mission Givers are the plethora or human, alien, kiosk, or any number of avenues"
It should read, "Mission Givers are the plethora of human, alien, kiosk, or any number of avenues"

(The 'or' should read as 'of')

**Comment by WiggL** [comment]
Final Editing Pass ---

"...Mission Givers may seem someone mundane or obscure, like that discarded piece of trash..."

Should read: "...Mission Givers may seem somewhat mundane or obscure, like that discarded piece of trash..."

('someone' should read 'somewhat')

Also, I was wondering what your thoughts were on first-person/third-person in regards to the 'voice' of the descriptions.  I'd like to get it all either one or the other.  Do you want it to read as if coming from CIG or coming from you?

**Comment by sweetcode** [comment]
Fixed & I prefer the first-person/third-person style.

**Comment by WiggL** [comment]
To clarify, write as if coming for you (1st) or CIG (3rd)?

**Comment by sweetcode** [comment]
You are right. I didn't notice that. I prefer the 1st person style that doesn't sound like its coming from CIG directly.
